### ISSUE TITLE
键盘不能铺满屏幕，请问怎么处理

### ISSUE THREAD

**Issue by androidzhangyu** [wengz/PinyinIME_Float#1]
项目运行后，键盘宽度少了一截。不能铺满

**Comment by wengz** [comment]
开发的时候针对的环境是大平板、带触控的大显示器等屏幕较大的设备，在小屏幕上会出现显示不全的异常。如果要在小屏上正常显示，要调整一下控件、布局等尺寸参数。你可以先新建一个大尺寸屏幕的模拟器看一下。
